### ISSUE TITLE
Integrate component with backend

### ISSUE THREAD

**Issue by Andrewwango** [Andrewwango/gds-accessible-search#9]
Call backend (running locally) from component function callBackend(). Possibly using async function. Possibly modify prompt (created in component) to use format given by system role (see https://learn.microsoft.com/en-gb/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions#managing-conversations)

**Comment by olliestanley** [comment]
This should be possible to work on now, the backend can be called at the URLs:

https://shwast-fun-app.azurewebsites.net/api/chatgpt

https://shwast-fun-app.azurewebsites.net/api/gpt

With parameter `input` for the prompt
